name: Swift

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      uses: fwal/setup-swift@v1
      run: swift build -c release -Xswiftc -g
