name: Swift

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: sudo apt update && sudo apt upgrade && sudo apt install -y binutils git gnupg2 libc6-dev libcurl4 libedit2 libgcc-9-dev libpython2.7 libsqlite3-0 libstdc++-9-dev libxml2 libz3-dev pkg-config tzdata zlib1g-dev
      
    - name: Download Swift
      run: wget https://swift.org/builds/swift-5.3.3-release/ubuntu2004/swift-5.3.3-RELEASE/swift-5.3.3-RELEASE-ubuntu20.04.tar.gz
      
    - name: Extract Swift
      run: tar -xvzf swift-5.3.3-RELEASE-ubuntu20.04.tar.gz -C . && echo "PATH=./swift-5.3.3-RELEASE-ubuntu20.04/usr/bin:$PATH" >> ~/.bashrc && . ~/.bashrc
    
    - name: Build
      run: swift build -c release -Xswiftc -g
